default: &default
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false

development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: gn_dev
  socket: /tmp/mysql.sock
  username: admin
  password: gathergather
  
test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: gn_test
  socket: /tmp/mysql.sock
  username: admin
  password: gathergather

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '') %>

